---
include:
#  - board: eyelash_corne_left
#    shield: nice_view
#    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: eyelash_corne_right
    shield: urchin_left nice_view_adapter  nice_view_custom #custom shield
    #shield: nice_view
    #snippet: zmk-usb-logging
  - board: eyelash_corne_left
    shield: urchin_right nice_view_adapter nice_view_custom #custom shield
    #shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_corne_studio_left
  - board: nice_nano_v2
    shield: settings_reset
    #snippet: zmk-usb-logging
